# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- development

pool:
  vmImage: ubuntu-latest
variables:
  - group: testing

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'Sonarcloud'
#     organization: 'jakzgit'
#     scannerMode: 'CLI'
#     configMode: 'manual'
#     cliProjectKey: 'JakZGit_gatsbyCypress'
#     cliProjectName: 'gatsbyCypress'
#     cliProjectVersion: '1.0'
#     cliSources: 'src'
#     extraProperties: |
#       sonar.javascript.lcov.reportPaths=./coverage/lcov.info
#       sonar.javascript.node.maxspace=8192

- script: |
    npm run dev
  displayName: 'run cypress'

- task: PublishPipelineArtifact@1
  displayName: 'Publish screenshots for failed test'
  condition: failed()
  inputs:
    artifactName: 'screenshots'
    targetPath: '$(System.DefaultWorkingDirectory)/cypress/screenshots'


# - task: PublishTestResults@2
#   condition: succeededOrFailed()
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: 'results/*.xml'
#     failTaskOnFailedTests: true


# - task: SonarCloudAnalyze@1

# # Uncomment the next task to wait until SonarCloud processing has
# # finished and to publish the result on the Pipeline build summary
# - task: SonarCloudPublish@1
#   inputs:
#    pollingTimeoutSec: '300'