on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "JakZGit/gatsbyCypress"
          source_branch: "*"
          destination_repo: "JakZGit/gatsbyCypress-Clone"
          destination_branch: "*"