on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:JakZGit/gatsbyCypress.git"
          source_branch: "*"
          destination_repo: "git@github.com:JakZGit/gatsbyCypress-Clone.git"
          destination_branch: "*"